# Generated by Django 3.2.3 on 2021-06-02 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time',
            field=models.IntegerField(default=1, help_text='duration of the quiz in minutes'),
        ),
    ]
