# Generated by Django 3.2.3 on 2021-06-03 04:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0002_quiz_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='question',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='quiz',
            name='number_of_questions',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quiz',
            name='required_score_to_pass',
            field=models.IntegerField(default=30, help_text='Minimum score required to pass the exam'),
        ),
    ]
